// src/lib/components/Snow.svelte
<script lang="ts">
  import { debounce } from "$lib/utils/debounce"
  import { onDestroy, onMount } from "svelte"

  let ctx!: CanvasRenderingContext2D
  let canvas!: HTMLCanvasElement
  const maxSpeed = 0.12

  function rand(min: number, max: number) {
    return Math.random() * (max - min) + min
  }

  function mod(n: number, d: number) {
    return ((n % d) + d) % d
  }

  function handleResize() {
    const oldWidth = canvas.width
    const oldHeight = canvas.height

    canvas.width = window.innerWidth
    canvas.height = window.innerHeight

    const scaleWidthBy = canvas.width / oldWidth
    const scaleHeightBy = canvas.height / oldHeight
    points.forEach((point) => {
      point.scalePosition(scaleWidthBy, scaleHeightBy)
    })

    renderFrame()
  }
  const debounceHandleResize = debounce(handleResize, 500)

  class Point {
    x: number
    y: number
    velocity: { x: number, y: number }
    readonly size: number
    readonly blur: number
    readonly alpha: number

    constructor() {
      this.x = rand(0, canvas.width)
      this.y = rand(0, canvas.height)
      this.velocity = {
        x: rand(-maxSpeed, maxSpeed),
        y: (rand(1, maxSpeed) + rand(1, maxSpeed)) / 2,
      }
      this.size = rand(0.5, 6)
      this.blur = (this.size * 2.5) + 2
      this.alpha = rand(0.1, 1)
    }

    drawPoint() {
      ctx.shadowBlur = this.blur
      ctx.globalAlpha = this.alpha
      ctx.fillStyle = "#ffffff7f"
      ctx.shadowColor = "#ffffffbf"
      ctx.beginPath()
      ctx.arc(
        this.x,
        this.y,
        this.size,
        0,
        360,
      )
      ctx.fill()
      ctx.closePath()
    }

    scalePosition(widthScale: number, heightScale: number) {
      this.x *= widthScale
      this.y *= heightScale
    }
  }

  let snowAmnt: number
  let points: Point[]

  function renderFrame() {
    ctx.clearRect(0, 0, canvas.width, canvas.height)
    points.forEach((i) => {
      i.x = mod((i.x + i.velocity.x), canvas.width)
      i.y = mod((i.y + i.velocity.y), canvas.height)
      i.drawPoint()
    })
  }
  let interval: number

  onMount(() => {
    canvas.width = window.innerWidth
    canvas.height = window.innerHeight
    ctx = canvas.getContext("2d")!
    snowAmnt = Math.floor((250 / 1920) * canvas.width)
    points = Array.from({ length: snowAmnt }, () => new Point())
    addEventListener("resize", debounceHandleResize)
    interval = setInterval(renderFrame, 10)
  })

  onDestroy(() => {
    removeEventListener("resize", debounceHandleResize)
    clearInterval(interval)
  })

</script>

<canvas bind:this={canvas}></canvas>

<style lang="scss">
  canvas {
    position: fixed;
    inset: 0;
    z-index: -1;
    width: calc(100vw + 1rem);
    height: calc(100vh + 1rem);
    left: -.5rem;
    top: -.5rem;
  }
</style>

// src/components/Snow.tsx
import { onCleanup, onMount } from 'solid-js'
import { mod, rand } from '../utils/functions.ts'
import '../styles/snow.scss'

interface Pos { x: number, y: number }

let canvas!: HTMLCanvasElement
let ctx!: CanvasRenderingContext2D
const flakeTexSize = 40
const maxSpeed = 0.012
let lastTime = 0
let animationId = 0
let renderPercentage = 1

function handleResize() {
  renderPercentage = Math.min(window.innerWidth / 3840, 1)
  const oldWidth = canvas.width
  const oldHeight = canvas.height

  canvas.width = window.innerWidth
  canvas.height = window.innerHeight

  const widthScalar = canvas.width / oldWidth
  const heightScalar = canvas.height / oldHeight
  let i = 0
  while (i < Flake.flakes.length) {
    const flake = Flake.flakes[i]
    flake.scalePosition(widthScalar, heightScalar)
    i++
  }
  ctx.fillStyle = '#0c0c0c'
}

class Flake {
  pos: Pos
  vel: Pos
  readonly size: number
  readonly blur: number
  readonly alpha: number
  readonly tex: OffscreenCanvas

  static flakes: Flake[] = []

  constructor() {
    this.pos = {
      x: rand(0, canvas.width),
      y: rand(0, canvas.height),
    }
    this.vel = {
      x: rand(-maxSpeed, maxSpeed),
      y: (rand(0.1, maxSpeed) + rand(0.1, maxSpeed)) / 2,
    }
    this.size = rand(0.5, 6)
    this.blur = (this.size * 2.5) + 2
    this.alpha = rand(0.1, 1)
    this.tex = this.makeFlakeTex()
    Flake.flakes.push(this)
  }

  makeFlakeTex(): OffscreenCanvas {
    const canvas = new OffscreenCanvas(flakeTexSize, flakeTexSize)
    const ctx = canvas.getContext('2d')!

    ctx.shadowBlur = this.blur
    ctx.globalAlpha = this.alpha
    ctx.fillStyle = '#ffffff7f'
    ctx.shadowColor = '#ffffffbf'

    ctx.beginPath()
    ctx.arc(
      flakeTexSize / 2,
      flakeTexSize / 2,
      this.size,
      0,
      360
    )
    ctx.fill()
    ctx.closePath()

    return canvas
  }

  move(deltaTime: number) {
    this.pos.x = mod(this.pos.x + this.vel.x * deltaTime, canvas.width)
    this.pos.y = mod(this.pos.y + this.vel.y * deltaTime, canvas.height)
  }

  scalePosition(widthScalar: number, heightScalar: number) {
    this.pos.x *= widthScalar
    this.pos.y *= heightScalar
  }
}

export function Snow() {
  function render(time: number) {
    const deltaTime = time - lastTime
    lastTime = time
    ctx.fillRect(0, 0, canvas.width, canvas.height)

    let i = 0
    while (i < Flake.flakes.length * renderPercentage) {
      const flake = Flake.flakes[i]
      flake.move(deltaTime)
      ctx.drawImage(flake.tex, flake.pos.x - flakeTexSize / 2, flake.pos.y - flakeTexSize / 2, flake.tex.width, flake.tex.height)
      i++
    }
    requestAnimationFrame(render)
  }

  onMount(() => {
    ctx = canvas.getContext('2d', { alpha: false })!
    handleResize()

    if (Flake.flakes.length === 0) {
      for (let i = 0; i < 500; i++)
        new Flake()
    }
    addEventListener('resize', handleResize)
    animationId = requestAnimationFrame(render)
  })
  onCleanup(() => {
    removeEventListener('resize', handleResize)
    cancelAnimationFrame(animationId)
  })

  return <canvas ref={canvas}>haiii</canvas>
}
